apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tas-agent-builder

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: agent-builder
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: tas

images:
- name: agent-builder
  newName: registry-api.tas.scharber.com/agent-builder
  newTag: latest
